services:
  api:
    environment:
      - DEBUG=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`localhost`)
      - traefik.http.routers.api.tls=false
      - traefik.http.routers.api.tls.certresolver=
      - traefik.http.services.api.loadbalancer.server.port=80
  
  mysql:
    ports:
      - "3306:3306"
    env_file: .env

    
  traefik:
    ports:
      - 80:80
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/traefik/traefik.dev.toml:/etc/traefik/traefik.toml
  
  elb:
    ports:
      - "1111:1111"
      - "3333:3333"
  
  vector:
    profiles:
      - "production" 

